/**
 * FAQ data for The Digital HQ (Website Development) page — plain data.
 */
export const DHQ_FAQS = [
  { q: 'What does a website development agency do?', a: 'A website development agency designs, builds and maintains websites. This includes planning the site structure, designing the user interface, writing the code, setting up the content management system, testing for performance and accessibility, and providing ongoing support. The agency connects business goals to a working website.' },
  { q: 'What is the difference between website design and website development?', a: 'Website design is about how the site looks and feels — layout, colours, typography, imagery and user experience. Website development is about how the site works — writing the code, building the functionality, setting up the CMS and making sure the site is fast, secure and reliable. Design shapes the experience; development makes it function.' },
  { q: 'Do you provide website design and development services?', a: 'Yes. We provide both website design and website development as one connected service. Our team handles strategy, UI/UX design, front-end development, back-end development and content management — so the design and the build are always aligned.' },
  { q: 'Do you offer responsive website development services?', a: 'Yes. Every website we build is responsive — designed to work cleanly across desktop, tablet and mobile. We design and test at common breakpoints so the experience adapts to the device, not just the screen size.' },
  { q: 'Do you develop WordPress websites?', a: 'Yes. We build WordPress websites for marketing sites, content-heavy publications and businesses that need an easy-to-manage CMS. We also work with other platforms and custom builds depending on the project requirements.' },
  { q: 'Is WordPress good for small businesses?', a: 'WordPress can be a good choice for small businesses — it is widely supported, has a large plugin ecosystem, and lets non-technical teams manage content. However, the right platform depends on the business, the budget and the long-term plan. We recommend the platform that fits the project, not the other way around.' },
  { q: 'Do you provide website development for small businesses?', a: 'Yes. We work with small businesses to build websites that are practical, affordable and built to grow. The scope scales to fit where the business is now — from a focused marketing site to a more complete platform.' },
  { q: 'Can you redesign my existing website?', a: "Yes. We redesign existing websites to improve design, performance, usability and content structure. We audit what exists, keep what works, and rebuild what doesn't — so the new site is a genuine improvement, not just a fresh coat of paint." },
  { q: 'How long does website development take?', a: 'Website development typically takes 4–10 weeks depending on scope — from a focused marketing site to a multi-page platform with custom functionality. We give a clear timeline after the discovery call.' },
  { q: 'Can you build an SEO-friendly website?', a: 'Yes. We build websites with a search-friendly structure — clean URLs, semantic HTML, fast loading, mobile responsiveness and proper heading hierarchy. We focus on the technical foundations that support SEO; we do not guarantee specific rankings.' },
]
