/**
 * FAQ data for The Hype Engine (Social Media) page — plain data.
 */
export const HYPE_FAQS = [
  { q: 'What does a social media agency do?', a: 'A social media agency plans, creates, publishes and manages content across social platforms. This includes strategy, content creation, community management, paid social advertising and performance analysis. The agency connects social activity to broader business goals so every post, campaign and interaction has a purpose.' },
  { q: 'What is the difference between a social media agency and a social media marketing agency?', a: 'A social media agency typically focuses on content creation, publishing and community management — keeping the brand active and present on social platforms. A social media marketing agency goes further, connecting social content to business goals through strategy, paid advertising, lead generation and performance measurement. watNidea works across both — from day-to-day content to strategy-led campaigns.' },
  { q: 'What social media marketing services do you provide?', a: 'We provide social media strategy, content creation, social media management, advertising, Instagram marketing, community management, campaign planning and analytics. Each service works on its own or as part of a connected social media plan.' },
  { q: 'Do you provide social media management?', a: 'Yes. We manage social media accounts — planning content calendars, creating posts, publishing on schedule, monitoring engagement and reporting on performance. Management can be full-service or focused on specific platforms.' },
  { q: 'Do you provide social media advertising?', a: 'Yes. We plan, create and manage paid social campaigns — including ad creative, audience targeting, budget management and performance tracking. We focus on strategy-led advertising, not guaranteed results.' },
  { q: 'Do you provide Instagram marketing?', a: 'Yes. We create Instagram-specific content — reels, carousels, stories and grid posts — designed for the platform\'s formats and audience behaviour. We also manage Instagram advertising and community engagement.' },
  { q: 'Do you provide social media marketing for small businesses?', a: 'Yes. We work with small businesses to build a practical, scalable social media presence. The scope fits where the business is now — from a focused content plan to full management across multiple platforms.' },
  { q: 'How often should a business post on social media?', a: 'Posting frequency depends on the platform, the audience and the business goals. Generally, consistency matters more than volume. We recommend a sustainable cadence — usually 3–5 posts per week per platform — and adjust based on engagement and performance.' },
  { q: 'How do you measure social media performance?', a: 'We track engagement (likes, comments, shares, saves), reach, follower growth, website traffic from social, and conversion actions (clicks, sign-ups, enquiries). We focus on metrics that connect to business goals, not vanity numbers. Performance is reported transparently — we don\'t guarantee specific results.' },
  { q: 'Which social media platforms should my business use?', a: 'The right platforms depend on where your audience spends time and what kind of content fits your brand. We typically recommend starting with 1–2 platforms and expanding as the strategy matures. Common choices include Instagram, Facebook, LinkedIn and YouTube — but the best mix is unique to each business.' },
]
